### ISSUE TITLE
Arch Linux Neon 0.34

### ISSUE THREAD

**Issue by lunix33** [alisarctl/davfs2#10]
On 2024-11-23, neon got its 0.34.

Currently this project isn't able to be built on Arch Linux since they updated the version of the library they are hosting.

Based on their changelog, they aren't listing any breaking changes.

**Comment by lunix33** [comment]
I just saw that there's a PR related to this issue.
#9

**Comment by alisarctl** [comment]
Support for neon 0.34 was added.
